title: TTS Arxiv Daily
description: Automatically update text-to-speech papers from arXiv every 12 hours
show_downloads: true

github:
  zip_url: https://github.com/liutaocode/TTS-arxiv-daily
  another_url: https://github.com/liutaocode/TTS-arxiv-daily

## add remote theme
remote_theme: jekyll/minima@v2.5.1

# minima:
skin: dark
social_links:
  github: liutaocode

plugins:
 - jekyll-remote-theme # add this line to the plugins list if you already have one
 - jekyll-feed
 - jekyll-seo-tag
